import '@/styles/globals.css';

import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Poppins, Raleway } from 'next/font/google';
import { PropsWithChildren } from 'react';

import { ThemeProvider } from '@/components/common/providers';
import { cn } from '@/lib/utils';

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--heading-font',
});

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--body-font',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('min-h-screen bg-background font-body antialiased', raleway.variable, poppins.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="relative flex min-h-screen flex-col bg-background">{children}</div>
          <SpeedInsights />
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
