import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Poppins, Raleway } from 'next/font/google';
import { FC, PropsWithChildren } from 'react';

import { DotBackground } from '@/components/ui/dot-background';
import { cn } from '@/lib/utils';
import { Providers } from '@/providers';

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--heading-font',
});

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--body-font',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('flex min-h-screen flex-col font-body', raleway.variable, poppins.variable)}>
        <Providers>
          <DotBackground>{children}</DotBackground>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
